name: Gerador Automatico do App n8n

on:
  workflow_dispatch:

jobs:
  criar-e-compilar:
    runs-on: ubuntu-latest

    steps:
    - name: 1️⃣ Baixar o Repositório
      uses: actions/checkout@v3

    - name: 2️⃣ Configurar o Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: 3️⃣ Instalar e Configurar o Capacitor
      run: |
        npm install
        npx capacitor init "Meu n8n Mobile" "com.meun8n.app" --web-dir=.
        npx capacitor add android

    - name: 4️⃣ Criar o arquivo APK do Android
      run: |
        cd android
        ./gradlew assembleDebug

    - name: 5️⃣ Liberar o download do teu .APK
      uses: actions/upload-artifact@v4
      with:
        name: meu-n8n-instalador-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
